# Generated by Django 5.1.2 on 2024-10-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_products',
            new_name='products',
        ),
    ]
