# Generated by Django 5.1.2 on 2024-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='стоимость'),
            preserve_default=False,
        ),
    ]
