# Generated by Django 5.1.2 on 2024-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('assembly', 'На сборке'), ('courier', 'Передан курьеру'), ('delivered', 'Доставлен')], db_index=True, default='unprocessed', max_length=30, verbose_name='Статус'),
        ),
    ]
