# Generated by Django 5.1.2 on 2024-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='комментарий'),
        ),
    ]
