# Generated by Django 5.1.2 on 2024-11-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_paymennt_alter_order_called_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymennt',
            new_name='payment',
        ),
    ]
