# Generated by Django 5.1.2 on 2025-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_rename_registrated_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('order_assembly', 'На сборке'), ('delivering', 'Передан курьеру'), ('delivered', 'Доставлен')], db_index=True, default='unprocessed', max_length=30, verbose_name='Статус'),
        ),
    ]
